### ISSUE TITLE
similar tools: fortran building tool

### ISSUE THREAD

**Issue by szaghi** [ZedThree/fort_depend.py#1]
Dear all,
I am working on a building tool tailored to fortran that incidentally generates also the inter-modules dependency (with full linarized hierachy and also tree-like form). Maybe it can be useful for you as your work is interesting for me:

https://github.com/szaghi/FoBiS

My best regards

**Comment by ZedThree** [comment]
Hi Stefano, nice project! I think I might use it for future Fortran projects. I'm glad you found our work interesting.

**Comment by szaghi** [comment]
@ZedThree sorry for my delay. Thanks for your comments.

Presently I have added support for submodules in FoBiS, that have indeed a sort of _inverse-dependency_ to their parent module. Maybe this is interesting for you.

At some point I will need to refactor-lint FoBiS, so I am going to study your code.

Thank you for sharing it!
