### ISSUE TITLE
false positives for module starts in continued args

### ISSUE THREAD

**Issue by stenczelt** [ZedThree/fort_depend.py#18]
if you run the program on the following module, then the line with `module_short_code` is picked up as a module beginning

```fortran
module aaa

implicit none

contains

    subroutine foo

        implicit none

        character(40) :: xyz, module_short_code


        xyz = "this &
                & module_short_code"

        call bar(xyz, &
             module_short_code &       ! this is picked up as a beginning
                )


    end subroutine foo

end module aaa
```

I think the regexp needs to be changed to have `\s+` rather than `\s*` after before the module name

**Comment by d7919** [comment]
To be explicit I guess it is the last `\s*`  at https://github.com/ZedThree/fort_depend.py/blob/ea2caf0010765f00de142d168b05665499ffe1ca/fortdepend/units.py#L6

**Comment by ZedThree** [comment]
Thanks for the bug report @stenczelt ! Please could you check #19 works for you? I've used a slightly modified form of your reproducer in the tests, but it looks like it works for me

**Comment by stenczelt** [comment]
Thanks a lot!
