### ISSUE TITLE
Ignored module names not case insenstive

### ISSUE THREAD

**Issue by lackyO3** [ZedThree/fort_depend.py#22]
Since Fortran is case insensitive shouldn't it be sufficient to include a module with arbitrary case?  If a collection of modules was written using inconsistent case in use statements than each case combination used needs to be listed after **-i**.

**Comment by ZedThree** [comment]
I have a fix for this, but it also changes how programs are written in the dependency file, as they would now all be lower case. I'm not sure if this would be a breaking change for users or not

**Comment by lackyO3** [comment]
I think your concern is well placed.   While Fortran is case insensitive the compiler will be sensitive the case of the file names in the dependency file.

**Comment by alphaskyler** [comment]
I recommend to read file contents and immediately change to lowercase.

contents = f.read().lower()

**Comment by ZedThree** [comment]
Should be fixed in #24
