### ISSUE TITLE
error when subroutine name matches substring of second subroutine

### ISSUE THREAD

**Issue by JeromeCCP9** [ZedThree/fort_depend.py#23]
If a subroutine name is substring of a second subroutine, then the matching pattern in units.py fails.

I think the issue is that the search pattern contains an optional space \s* that should not be optional, so should be \s+

For me this tiny change fixes the issue, perhaps useful for others also.
Yours, with many thanks,
Jerome Jackson.

`--- units.py	2022-02-15 23:09:14.390686912 +0000
+++ units-fix.py	2022-02-15 23:10:32.233272253 +0000
@@ -3,7 +3,7 @@

 from .smartopen import smart_open

-UNIT_REGEX = re.compile(r"^\s*(?P<unit_type>module(?!\s+procedure)|program)\s*(?P<modname>\w*)",
+UNIT_REGEX = re.compile(r"^\s*(?P<unit_type>module(?!\s+procedure)|program)\s+(?P<modname>\w*)",
                         re.IGNORECASE)
 END_REGEX = re.compile(r"^\s*end\s*(?P<unit_type>module|program)\s*(?P<modname>\w*)?",
                        re.IGNORECASE)`

**Comment by ZedThree** [comment]
This should be fixed in #19 and in the latest 2.1.0 release

Please reopen this if it's still not working for you! If so, an example case would be lovely :)
