### ISSUE TITLE
Variables starting with the word "use"

### ISSUE THREAD

**Issue by gkenway** [ZedThree/fort_depend.py#7]
I just started to try out fort_depend.py. It looks quite promising!

I ran into a small minor issue with the parsing of use statements. If I understand correctly, the regex for matching the "use <modulename>" is the following:

`p=re.compile("^\s*use\s*(?P<moduse>\w*)\s*(,)?\s*(only)?\s*(:)?.*?$",re.IGNORECASE).match`

However, this will also match variables such as "useTranspose" and it will give an error such as

Error module Transpose not defined in any files. Skipping...

This doesn't actually affect the end result, but it does mean you have to check that they are not actually errors. 

Instead, I think the following modification would work better:

`p=re.compile("^\s*use\s+(?P<moduse>\w*)\s*(,)?\s*(only)?\s*(:)?.*?$",re.IGNORECASE).match`

The second '*' is replaced with '+' meaning "1 or more".  Without a space, the line is not a valid Fortran use statement anyway. It also then doesn't pickup variables that start with use. For the code I'm working on this, completely fixed the issue. 

Thanks
Gaetan

**Comment by ZedThree** [comment]
Hi Gaetan, sorry for taking ages to get back to you, I've been on holiday.

Good catch! Unfortunately, there's a slight complication, the following is valid Fortran:

```
 use::foo
```

So I think we actually need a regex that checks _either_ for whitespace or `::`. Actually, I've been almost completely rewriting fort_depend, and currently have a regex that looks like:

```
"^\s*use(\s*,\s*intrinsic\s*::)?\s*(?P<moduse>\w*)\s*(, )?\s*(only)?\s*(:)?.*?$"
```

This captures things like

```
use, intrinsic :: iso_c_binding, only : c_int
```

but will still fail on `useTranspose`.

---

It looks like having `(\s*::\s*|\s+)` does what we want.

**Comment by gkenway** [comment]
Great. I've never used the use:: syntax before and never thought of it.

By the way, I managed to get fort_depend.py integrated into my build system for a fairly large 180k line fortran code and it works perfectly.

Gaetan
